#services:
##    admin.example:
##        class: AdminBundle\Example
##        arguments: ["@service_id", "plain_value", %parameter%]
#
#    admin.admin.test:
#        class: AppBundle\Admin\TestAdmin
#        arguments: [~, AppBundle\Entity\Test, AppBundle:TestAdmin]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }
